package projectm

// types.h

const (
	PROJECTM_MONO   = 1
	PROJECTM_STEREO = 2
)

const (
	PROJECTM_CHANNEL_L = 0
	PROJECTM_CHANNEL_0 = 0
	PROJECTM_CHANNEL_R = 1
	PROJECTM_CHANNEL_1 = 1
)

const (
	PROJECTM_TOUCH_TYPE_RANDOM = iota
	PROJECTM_TOUCH_TYPE_CIRCLE
	PROJECTM_TOUCH_TYPE_RADIAL_BLOB
	PROJECTM_TOUCH_TYPE_BLOB2
	PROJECTM_TOUCH_TYPE_BLOB3
	PROJECTM_TOUCH_TYPE_DERIVATIVE_LINE
	PROJECTM_TOUCH_TYPE_BLOB5
	PROJECTM_TOUCH_TYPE_LINE
	PROJECTM_TOUCH_TYPE_DOUBLE_LINE
)

// playlist_types.h

const (
	SORT_PREDICATE_FULL_PATH = iota
	SORT_PREDICATE_FILENAME_ONLY
)

const (
	SORT_ORDER_ASCENDING = iota
	SORT_ORDER_DESCENDING
)
